site_name: Web Scraper Docs
repo_url: https://github.com/PhilNel/docs-web-scraper
site_url: https://PhilNel.github.io/docs-web-scraper

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
  - Features:
      - HTML Fetching: features/html-fetching.md
      - HTML Parsing: features/html-parsing.md