name: Deploy MkDocs to Github Pages

on:
  push:
      branches:
        - main

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        
        - name: Install dependencies
          run: |
            pip install mkdocs-material mkdocs-mermaid2-plugin
        
        - name: Deploy on GitHub Pages
          run: mkdocs gh-deploy --force
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}